// esbuild.config.mjs
import esbuild from 'esbuild';
import process from 'node:process';
import { builtinModules } from 'node:module';  // Node 18+ native

const isProd = process.argv[2] === 'production';

esbuild
  .build({
    banner: {
      js: `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Source: https://github.com/YOURUSERNAME/obsidian-sleep-log
*/`
    },
    entryPoints: ['src/main.ts'],
    outfile: 'main.js',
    external: ['obsidian'],
    format: 'cjs',
    target: 'es2020',
    sourcemap: isProd ? false : 'inline',
    bundle: true,
    platform: 'node',
    logLevel: 'info',
  })
  .then(() => console.log('✅ Build complete!'))
  .catch((e) => {
    console.error('❌ Build failed:', e);
    process.exit(1);
  });
